 
const products =  [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    price: 1499,
    category: "Electronics",
    brand: "SoundMax",
    stock: 25,
    rating: 4.5,
    description: "Comfortable wireless headphones with clear sound and long battery life.",
    image: "https://example.com/images/wireless-headphones.jpg"
  },
  {
    id: 2,
    name: "Smart Watch Series 5",
    price: 2499,
    category: "Electronics",
    brand: "TechTime",
    stock: 18,
    rating: 4.3,
    description: "Smart watch with fitness tracking, notifications and heart-rate monitoring.",
    image: "https://example.com/images/smart-watch.jpg"
  },
  {
    id: 3,
    name: "Wireless Gaming Mouse",
    price: 899,
    category: "Computer Accessories",
    brand: "GamePro",
    stock: 40,
    rating: 4.6,
    description: "Ergonomic wireless gaming mouse with adjustable DPI.",
    image: "https://example.com/images/gaming-mouse.jpg"
  },
  {
    id: 4,
    name: "Mechanical Gaming Keyboard",
    price: 1799,
    category: "Computer Accessories",
    brand: "KeyMaster",
    stock: 20,
    rating: 4.7,
    description: "Mechanical keyboard with RGB lighting and responsive keys.",
    image: "https://example.com/images/gaming-keyboard.jpg"
  },
  {
    id: 5,
    name: "USB-C Fast Charger",
    price: 699,
    category: "Electronics",
    brand: "PowerTech",
    stock: 50,
    rating: 4.4,
    description: "Compact fast charger with USB-C output for smartphones and tablets.",
    image: "https://example.com/images/usb-c-charger.jpg"
  },
  {
    id: 6,
    name: "Power Bank 20000mAh",
    price: 1299,
    category: "Electronics",
    brand: "PowerMax",
    stock: 30,
    rating: 4.5,
    description: "High-capacity power bank with dual USB charging ports.",
    image: "https://example.com/images/power-bank.jpg"
  },
  {
    id: 7,
    name: "Bluetooth Portable Speaker",
    price: 1199,
    category: "Electronics",
    brand: "BeatBox",
    stock: 35,
    rating: 4.2,
    description: "Portable Bluetooth speaker with powerful sound and compact design.",
    image: "https://example.com/images/bluetooth-speaker.jpg"
  },
  {
    id: 8,
    name: "Full HD Web Camera",
    price: 999,
    category: "Computer Accessories",
    brand: "VisionCam",
    stock: 22,
    rating: 4.3,
    description: "1080p webcam suitable for video calls, meetings and streaming.",
    image: "https://example.com/images/web-camera.jpg"
  },
  {
    id: 9,
    name: "Laptop Backpack",
    price: 899,
    category: "Bags",
    brand: "UrbanCarry",
    stock: 45,
    rating: 4.6,
    description: "Water-resistant backpack with a dedicated laptop compartment.",
    image: "https://example.com/images/laptop-backpack.jpg"
  },
  {
    id: 10,
    name: "Wireless Earbuds",
    price: 1599,
    category: "Electronics",
    brand: "SoundMax",
    stock: 28,
    rating: 4.4,
    description: "True wireless earbuds with charging case and touch controls.",
    image: "https://example.com/images/wireless-earbuds.jpg"
  },

  {
    id: 11,
    name: "Men's Casual T-Shirt",
    price: 499,
    category: "Men's Clothing",
    brand: "UrbanWear",
    stock: 60,
    rating: 4.2,
    description: "Comfortable cotton casual t-shirt for everyday wear.",
    image: "https://example.com/images/mens-tshirt.jpg"
  },
  {
    id: 12,
    name: "Men's Denim Jeans",
    price: 1299,
    category: "Men's Clothing",
    brand: "DenimCo",
    stock: 35,
    rating: 4.5,
    description: "Classic slim-fit denim jeans with durable fabric.",
    image: "https://example.com/images/mens-jeans.jpg"
  },
  {
    id: 13,
    name: "Men's Formal Shirt",
    price: 899,
    category: "Men's Clothing",
    brand: "ClassicFit",
    stock: 30,
    rating: 4.3,
    description: "Smart formal shirt suitable for office and professional occasions.",
    image: "https://example.com/images/formal-shirt.jpg"
  },
  {
    id: 14,
    name: "Men's Hoodie",
    price: 1099,
    category: "Men's Clothing",
    brand: "StreetStyle",
    stock: 25,
    rating: 4.6,
    description: "Warm and comfortable hoodie with a modern casual design.",
    image: "https://example.com/images/mens-hoodie.jpg"
  },
  {
    id: 15,
    name: "Men's Sports Shoes",
    price: 1899,
    category: "Footwear",
    brand: "RunX",
    stock: 20,
    rating: 4.5,
    description: "Lightweight sports shoes designed for running and daily workouts.",
    image: "https://example.com/images/mens-sports-shoes.jpg"
  },
  {
    id: 16,
    name: "Men's Leather Wallet",
    price: 599,
    category: "Accessories",
    brand: "LeatherCraft",
    stock: 40,
    rating: 4.4,
    description: "Compact wallet with multiple card slots and cash compartment.",
    image: "https://example.com/images/mens-wallet.jpg"
  },
  {
    id: 17,
    name: "Men's Sunglasses",
    price: 699,
    category: "Accessories",
    brand: "SunStyle",
    stock: 32,
    rating: 4.1,
    description: "Stylish sunglasses with UV protection.",
    image: "https://example.com/images/mens-sunglasses.jpg"
  },
  {
    id: 18,
    name: "Men's Analog Watch",
    price: 1499,
    category: "Accessories",
    brand: "TimePro",
    stock: 15,
    rating: 4.5,
    description: "Classic analog watch with a premium-looking design.",
    image: "https://example.com/images/mens-watch.jpg"
  },
  {
    id: 19,
    name: "Men's Cotton Shorts",
    price: 599,
    category: "Men's Clothing",
    brand: "UrbanWear",
    stock: 45,
    rating: 4.2,
    description: "Comfortable cotton shorts suitable for casual everyday use.",
    image: "https://example.com/images/mens-shorts.jpg"
  },
  {
    id: 20,
    name: "Men's Running Jacket",
    price: 1399,
    category: "Men's Clothing",
    brand: "RunX",
    stock: 18,
    rating: 4.4,
    description: "Lightweight sports jacket designed for outdoor activities.",
    image: "https://example.com/images/running-jacket.jpg"
  },

  {
    id: 21,
    name: "Women's Casual Top",
    price: 599,
    category: "Women's Clothing",
    brand: "StyleHub",
    stock: 50,
    rating: 4.3,
    description: "Comfortable and stylish casual top for everyday wear.",
    image: "https://example.com/images/womens-top.jpg"
  },
  {
    id: 22,
    name: "Women's Denim Jeans",
    price: 1299,
    category: "Women's Clothing",
    brand: "DenimCo",
    stock: 32,
    rating: 4.5,
    description: "Modern-fit denim jeans with comfortable stretch fabric.",
    image: "https://example.com/images/womens-jeans.jpg"
  },
  {
    id: 23,
    name: "Women's Handbag",
    price: 1199,
    category: "Bags",
    brand: "StyleHub",
    stock: 25,
    rating: 4.6,
    description: "Elegant handbag with multiple compartments for daily essentials.",
    image: "https://example.com/images/womens-handbag.jpg"
  },
  {
    id: 24,
    name: "Women's Sneakers",
    price: 1699,
    category: "Footwear",
    brand: "WalkPro",
    stock: 22,
    rating: 4.4,
    description: "Comfortable sneakers suitable for casual and everyday use.",
    image: "https://example.com/images/womens-sneakers.jpg"
  },
  {
    id: 25,
    name: "Women's Sunglasses",
    price: 799,
    category: "Accessories",
    brand: "SunStyle",
    stock: 35,
    rating: 4.2,
    description: "Fashionable sunglasses with UV protection.",
    image: "https://example.com/images/womens-sunglasses.jpg"
  },
  {
    id: 26,
    name: "Women's Wrist Watch",
    price: 1399,
    category: "Accessories",
    brand: "TimePro",
    stock: 20,
    rating: 4.5,
    description: "Elegant wrist watch designed for everyday and formal occasions.",
    image: "https://example.com/images/womens-watch.jpg"
  },
  {
    id: 27,
    name: "Women's Hoodie",
    price: 999,
    category: "Women's Clothing",
    brand: "StreetStyle",
    stock: 28,
    rating: 4.4,
    description: "Soft and comfortable hoodie with a casual modern style.",
    image: "https://example.com/images/womens-hoodie.jpg"
  },
  {
    id: 28,
    name: "Women's Sports Leggings",
    price: 699,
    category: "Women's Clothing",
    brand: "FitLife",
    stock: 40,
    rating: 4.3,
    description: "Stretchable sports leggings designed for workouts and yoga.",
    image: "https://example.com/images/sports-leggings.jpg"
  },
  {
    id: 29,
    name: "Women's Backpack",
    price: 999,
    category: "Bags",
    brand: "UrbanCarry",
    stock: 30,
    rating: 4.5,
    description: "Lightweight backpack with multiple storage compartments.",
    image: "https://example.com/images/womens-backpack.jpg"
  },
  {
    id: 30,
    name: "Women's Sandals",
    price: 799,
    category: "Footwear",
    brand: "WalkPro",
    stock: 35,
    rating: 4.2,
    description: "Comfortable casual sandals suitable for everyday use.",
    image: "https://example.com/images/womens-sandals.jpg"
  },

  {
    id: 31,
    name: "Ceramic Coffee Mug",
    price: 299,
    category: "Home & Kitchen",
    brand: "HomeStyle",
    stock: 70,
    rating: 4.5,
    description: "Durable ceramic coffee mug with a simple modern design.",
    image: "https://example.com/images/coffee-mug.jpg"
  },
  {
    id: 32,
    name: "Stainless Steel Water Bottle",
    price: 599,
    category: "Home & Kitchen",
    brand: "HydroMax",
    stock: 55,
    rating: 4.6,
    description: "Reusable stainless steel bottle that keeps drinks fresh.",
    image: "https://example.com/images/water-bottle.jpg"
  },
  {
    id: 33,
    name: "Non-Stick Frying Pan",
    price: 899,
    category: "Home & Kitchen",
    brand: "KitchenPro",
    stock: 25,
    rating: 4.4,
    description: "Non-stick frying pan suitable for everyday cooking.",
    image: "https://example.com/images/frying-pan.jpg"
  },
  {
    id: 34,
    name: "Electric Kettle 1.5L",
    price: 999,
    category: "Home Appliances",
    brand: "HomeTech",
    stock: 30,
    rating: 4.5,
    description: "Fast-boiling electric kettle with automatic shut-off.",
    image: "https://example.com/images/electric-kettle.jpg"
  },
  {
    id: 35,
    name: "Table Lamp",
    price: 699,
    category: "Home Decor",
    brand: "GlowHome",
    stock: 35,
    rating: 4.3,
    description: "Modern table lamp suitable for bedrooms and study tables.",
    image: "https://example.com/images/table-lamp.jpg"
  },
  {
    id: 36,
    name: "LED String Lights",
    price: 399,
    category: "Home Decor",
    brand: "GlowHome",
    stock: 60,
    rating: 4.4,
    description: "Decorative LED string lights for bedrooms and special occasions.",
    image: "https://example.com/images/led-string-lights.jpg"
  },
  {
    id: 37,
    name: "Kitchen Storage Containers",
    price: 799,
    category: "Home & Kitchen",
    brand: "KitchenPro",
    stock: 40,
    rating: 4.5,
    description: "Set of airtight storage containers for kitchen organization.",
    image: "https://example.com/images/storage-containers.jpg"
  },
  {
    id: 38,
    name: "Cotton Bedsheet",
    price: 999,
    category: "Home & Kitchen",
    brand: "HomeStyle",
    stock: 25,
    rating: 4.3,
    description: "Soft cotton bedsheet with a comfortable and stylish design.",
    image: "https://example.com/images/bedsheet.jpg"
  },
  {
    id: 39,
    name: "Wall Clock",
    price: 599,
    category: "Home Decor",
    brand: "TimePro",
    stock: 30,
    rating: 4.2,
    description: "Simple modern wall clock suitable for home and office spaces.",
    image: "https://example.com/images/wall-clock.jpg"
  },
  {
    id: 40,
    name: "Decorative Plant Pot",
    price: 349,
    category: "Home Decor",
    brand: "GreenHome",
    stock: 45,
    rating: 4.4,
    description: "Stylish decorative plant pot for indoor and balcony plants.",
    image: "https://example.com/images/plant-pot.jpg"
  },

  {
    id: 41,
    name: "Yoga Mat",
    price: 599,
    category: "Sports",
    brand: "FitLife",
    stock: 40,
    rating: 4.6,
    description: "Non-slip yoga mat designed for yoga, stretching and workouts.",
    image: "https://example.com/images/yoga-mat.jpg"
  },
  {
    id: 42,
    name: "Football",
    price: 799,
    category: "Sports",
    brand: "SportPro",
    stock: 25,
    rating: 4.5,
    description: "Durable football suitable for training and recreational games.",
    image: "https://example.com/images/football.jpg"
  },
  {
    id: 43,
    name: "Cricket Bat",
    price: 1499,
    category: "Sports",
    brand: "SportPro",
    stock: 18,
    rating: 4.4,
    description: "Lightweight cricket bat suitable for beginners and casual players.",
    image: "https://example.com/images/cricket-bat.jpg"
  },
  {
    id: 44,
    name: "Skipping Rope",
    price: 299,
    category: "Fitness",
    brand: "FitLife",
    stock: 55,
    rating: 4.3,
    description: "Adjustable skipping rope for cardio and home workouts.",
    image: "https://example.com/images/skipping-rope.jpg"
  },
  {
    id: 45,
    name: "Gym Gloves",
    price: 399,
    category: "Fitness",
    brand: "FitLife",
    stock: 35,
    rating: 4.2,
    description: "Comfortable workout gloves with grip support for gym training.",
    image: "https://example.com/images/gym-gloves.jpg"
  },
  {
    id: 46,
    name: "Resistance Bands Set",
    price: 699,
    category: "Fitness",
    brand: "FitLife",
    stock: 30,
    rating: 4.5,
    description: "Set of resistance bands for strength training and home workouts.",
    image: "https://example.com/images/resistance-bands.jpg"
  },
  {
    id: 47,
    name: "Running Shoes",
    price: 1999,
    category: "Footwear",
    brand: "RunX",
    stock: 20,
    rating: 4.6,
    description: "Lightweight running shoes with comfortable cushioning.",
    image: "https://example.com/images/running-shoes.jpg"
  },
  {
    id: 48,
    name: "Sports Water Bottle",
    price: 499,
    category: "Sports",
    brand: "HydroMax",
    stock: 50,
    rating: 4.4,
    description: "Durable sports bottle designed for workouts and outdoor activities.",
    image: "https://example.com/images/sports-bottle.jpg"
  },
  {
    id: 49,
    name: "Dumbbell Set 10kg",
    price: 1799,
    category: "Fitness",
    brand: "FitLife",
    stock: 15,
    rating: 4.5,
    description: "10kg adjustable dumbbell set for strength training at home.",
    image: "https://example.com/images/dumbbell-set.jpg"
  },
  {
    id: 50,
    name: "Sports Gym Bag",
    price: 899,
    category: "Sports",
    brand: "SportPro",
    stock: 30,
    rating: 4.3,
    description: "Spacious gym bag with separate compartments for sports essentials.",
    image: "https://example.com/images/gym-bag.jpg"
  }
];

module.exports =  products; 